In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy  as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a= np.array([1,2,4,5])
a

array([1, 2, 4, 5])

In [5]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[0]

array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.empty(2)

array([1., 1.])

In [10]:
np.arange(4)


array([0, 1, 2, 3])

In [15]:
np.arange(4,20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(2,20,5)

array([ 2,  7, 12, 17])

In [21]:
np.linspace(2,10, num=4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [25]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [26]:
arr= np.array([3,2,1])
np.sort(arr)

array([1, 2, 3])

In [27]:
a= np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [30]:
#axis
a=([[1,2],[2,3]])
b=([[4,5]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [2, 3],
       [4, 5]])

In [34]:
a=np.array([[[1,2,3,4],[2,3,4,6]],[[3,4,5,6],[4,5,6,7]]])
a.ndim


3

In [35]:
a.size

16

In [36]:
a.shape

(2, 2, 4)

In [40]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [41]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [51]:
c=np.array([1,2,3,4,5,6])
print(c)

[1 2 3 4 5 6]


In [54]:
c.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [56]:
a[0:2]


array([0, 1])

In [57]:
a[3]

np.int64(3)

In [60]:
a.max()

np.int64(5)

In [61]:
a.min()

np.int64(0)

In [62]:
a.sum()

np.int64(15)

In [70]:
a=np.array([[2,3],[2,3],[7,8]])
a[2,1]

np.int64(8)

In [71]:
np.__version__


'2.1.3'

In [73]:
# List to array
a=[1,2,3,4]
b= np.array(a)
b

array([1, 2, 3, 4])

In [74]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [77]:
np.arange(0,56)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [78]:
np.arange(-20,20)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19])

In [79]:
np.arange(-20,20,2)

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,
         6,   8,  10,  12,  14,  16,  18])

In [80]:
#Random
np.random.rand(5)

array([0.37056449, 0.87803676, 0.11257626, 0.24145187, 0.6306793 ])

In [82]:
np.random.randint(2,8,2)

array([7, 6], dtype=int32)

In [83]:
#reshape
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
#slicing
g=np.random.randint(10,20,(5,4))

In [88]:
g[:]

array([[14, 18, 10, 15],
       [15, 10, 19, 19],
       [16, 11, 11, 12],
       [13, 18, 17, 12],
       [15, 10, 14, 18]], dtype=int32)

In [89]:
#revel or flatten
f1=np.array([[1,2],[2,3]])
np.ravel(f1)

array([1, 2, 2, 3])

In [92]:
#transpose
e1=np.array([[1,4],[2,3]])
np.transpose(e1)

array([[1, 2],
       [4, 3]])

In [94]:
#stack
a=np.array([1,2])
b=np.array([3,4])
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [95]:
a*2

array([2, 4])

In [96]:
a+4

array([5, 6])

In [97]:
a-2

array([-1,  0])

In [98]:
a/1

array([1., 2.])

In [99]:
a//1

array([1, 2])